server:
  tomcat:
    relaxed-query-chars: ['[',']']
spring:
  datasource:
    password: Welcome90
    url: jdbc:postgresql://localhost:5432/quickshare
    username: postgres
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet: 
    multipart: 
       enabled: true 
       file-size-threshold: 200KB   
       max-file-size:       -1 
       max-request-size:    -1 